# Simple workflow for deploying static content to GitHub Pages
name: build and update repo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  schedule:
    # Runs "At 06:30 on Tuesday." (see https://crontab.guru)
    - cron: '30 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          #go-version-file: go.mod
          go-version: 'stable'

      - name: binutils-mips-linux-gnu
        run: sudo apt-get update && sudo apt-get install -y binutils-mips-linux-gnu
      
      - name: Build IPK files
        run: ./build.sh "${{ github.event_name }}"

       # Only deploy if new version
      - name: Check new package existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "packages/19.07/Packages"
      
      - name: Prep GH Pages Directory
        if: ${{ (github.ref == 'refs/heads/main') && (steps.check_files.outputs.files_exists == 'true') }}
        run: |
          cp -r ./html ./gh_pages
          mv ./packages/ gh_pages/packages/
          ./tools/gen_directory_listing.sh ./gh_pages/packages/19.07/
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ (github.ref == 'refs/heads/main') && (steps.check_files.outputs.files_exists == 'true') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh_pages
          force_orphan: true # do not keep history
      
